name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: composer update --no-progress --no-suggest
    - name: Generate key
      run: php artisan key:generate
    
