name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Deploy to DigitalOcean
        run: |
          echo 'yes' | ssh -T root@157.230.221.252
          