name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master    
    - name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client
        with:
          mysql-host: 127.0.0.1
          mysql-port: 3306
          mysql-user: root
          mysql-password: password
          mysql-database: lara8

    - name: Check MySQL connection
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p password -e "SELECT 1;"
