name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  database-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      -name: Set up MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server -y
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
      - name: Check MySQL connection
        run: echo "password" | mysql -u root -p;