name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer update
    - name: Run artisan db migrate
      run: |
        echo "yes" | php artisan migrate
  