name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  database-migrate:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lara8
        ports:
          - 3306:3306

    steps:
      - name: Install MySQL Client
        run: sudo apt-get install mysql-client

      - name: Check MySQL connection
        run: |
          echo "password" | mysql -h 127.0.0.1 -P 3306 -u root -p
