name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer update
    - name: Run artisan db:seed
      run: |
        php artisan db:seed 
        php artisan cache:clear
    
