name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        run: |
          # Replace with your specific deployment command
          sshpass -p ww_*ES7Tf?$7N12 ssh root@157.230.221.252 "cd /var/www/html/sanad"